---
# Vishakh's ansible setup script
# local.yml is used for pull-based Ansible setup.

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - btop
        - tmux
        - python3
        - git
        - curl
        - wget


